### PR TITLE
Fetch data

### PR DESCRIPTION
**Pull request by shlomomdahan**
Screenshot 2024-05-27 at 6 15 29 PM

Screenshot 2024-05-27 at 6 19 50 PM

Screenshot 2024-05-27 at 6 20 34 PM

Updates include:

- dynamically fetch data directly from the source. (no more data files stored in our repo)
- dramatically update the stats page look and feel. Going for a minimal/modern look
- update landing page to match style from stats page
- fix responsiveness issues
- cleanup/refactor code into separate components / hooks to reduce bulkiness of components. Especially for stats page, I broke out the drawer into its own component and created separate hook files to manage those respective states.

Please review when you have a chance and provide any comments and fixes.

Thanks

### CODE REVIEW

**Comment by Vandit1604** [comment]
@shlomomdahan On large screen, the design looks fantastic.

**Comment by Vandit1604** [comment]
I'm curious about how you intend to display the dashboard/data charts on smaller screens, like smartphones.

**Comment by shlomomdahan** [comment]
@Vandit1604 Thank you! 

@krisstern and I discussed the issue with smaller screens.. I think we decided that we will have a reduced version for phones etc. as this app really is not designed for mobile. I think given the amount of data we are trying to display and analyze, it really will be an app focused for desktop view. 

However, I am open to fine tuning the responsiveness and getting something to work for mobile. Any suggestions?

**Comment by Vandit1604** [comment]
No suggestions as of now. Reduced version for mobiles is the way to go.

**Comment by krisstern** [comment]
Hi @shlomomdahan, maybe we should wait until we have more time review the code before merging next time?

**Pull request merged**
